name: continuous deployment

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      GO_ENV: production
      SERVER_PORT: 8000
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSLMODE: require
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Build AWS Lambda Server
        run: make buildlambda
      - name: Migrate Database
        run: make migratedb
      - name: Deploy to AWS Lambda
        run: serverless deploy
